//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balancas.BalancasWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Localizacao", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Localizacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BalancasWS.BalancasSoap")]
    public interface BalancasSoap {
        
        // CODEGEN: Generating message contract since element name BalancasParaRecolherResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BalancasParaRecolher", ReplyAction="*")]
        Balancas.BalancasWS.BalancasParaRecolherResponse BalancasParaRecolher(Balancas.BalancasWS.BalancasParaRecolherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BalancasParaRecolher", ReplyAction="*")]
        System.Threading.Tasks.Task<Balancas.BalancasWS.BalancasParaRecolherResponse> BalancasParaRecolherAsync(Balancas.BalancasWS.BalancasParaRecolherRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BalancasParaRecolherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BalancasParaRecolher", Namespace="http://tempuri.org/", Order=0)]
        public Balancas.BalancasWS.BalancasParaRecolherRequestBody Body;
        
        public BalancasParaRecolherRequest() {
        }
        
        public BalancasParaRecolherRequest(Balancas.BalancasWS.BalancasParaRecolherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BalancasParaRecolherRequestBody {
        
        public BalancasParaRecolherRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BalancasParaRecolherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BalancasParaRecolherResponse", Namespace="http://tempuri.org/", Order=0)]
        public Balancas.BalancasWS.BalancasParaRecolherResponseBody Body;
        
        public BalancasParaRecolherResponse() {
        }
        
        public BalancasParaRecolherResponse(Balancas.BalancasWS.BalancasParaRecolherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BalancasParaRecolherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Balancas.BalancasWS.Localizacao[] BalancasParaRecolherResult;
        
        public BalancasParaRecolherResponseBody() {
        }
        
        public BalancasParaRecolherResponseBody(Balancas.BalancasWS.Localizacao[] BalancasParaRecolherResult) {
            this.BalancasParaRecolherResult = BalancasParaRecolherResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BalancasSoapChannel : Balancas.BalancasWS.BalancasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BalancasSoapClient : System.ServiceModel.ClientBase<Balancas.BalancasWS.BalancasSoap>, Balancas.BalancasWS.BalancasSoap {
        
        public BalancasSoapClient() {
        }
        
        public BalancasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BalancasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BalancasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BalancasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balancas.BalancasWS.BalancasParaRecolherResponse Balancas.BalancasWS.BalancasSoap.BalancasParaRecolher(Balancas.BalancasWS.BalancasParaRecolherRequest request) {
            return base.Channel.BalancasParaRecolher(request);
        }
        
        public Balancas.BalancasWS.Localizacao[] BalancasParaRecolher() {
            Balancas.BalancasWS.BalancasParaRecolherRequest inValue = new Balancas.BalancasWS.BalancasParaRecolherRequest();
            inValue.Body = new Balancas.BalancasWS.BalancasParaRecolherRequestBody();
            Balancas.BalancasWS.BalancasParaRecolherResponse retVal = ((Balancas.BalancasWS.BalancasSoap)(this)).BalancasParaRecolher(inValue);
            return retVal.Body.BalancasParaRecolherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Balancas.BalancasWS.BalancasParaRecolherResponse> Balancas.BalancasWS.BalancasSoap.BalancasParaRecolherAsync(Balancas.BalancasWS.BalancasParaRecolherRequest request) {
            return base.Channel.BalancasParaRecolherAsync(request);
        }
        
        public System.Threading.Tasks.Task<Balancas.BalancasWS.BalancasParaRecolherResponse> BalancasParaRecolherAsync() {
            Balancas.BalancasWS.BalancasParaRecolherRequest inValue = new Balancas.BalancasWS.BalancasParaRecolherRequest();
            inValue.Body = new Balancas.BalancasWS.BalancasParaRecolherRequestBody();
            return ((Balancas.BalancasWS.BalancasSoap)(this)).BalancasParaRecolherAsync(inValue);
        }
    }
}
